### ISSUE TITLE
Test case assert API is non-intuitive

### ISSUE THREAD

**Issue by esoterra** [yusuf8ahmed/Wasmite#1]
I have a few notes/suggestions on this
1. `assertTypes` and `types` are used specifically for arguments, but their name does not communicate this.
2. I'm not sure why `types` and `result` are necessary, I generally trust people to construct lists on their own.
3. I think there would be value offering a `FuncType` typed `NamedTuple` class and offering a combined `assertFuncType` that compares this value to the params and result of the provided value.
e.g.
```python
class FuncType(NamedTuple):
    args: List[Type]
    result: Type
...
class WasmiteCase(unittest.TestCase):
    ...
    def assertFuncType(self, func, func_type):
        assert func.type.params == func_type.params
        assert func.type.results == func_type.result
```

```python
class Test(wasmite.TestWasm):
    ...
    def test_args_add(self):
        # check that the param types of the function "add" is I32, I32
        add_function = self.exports.add
        self.assertFuncType(add_function, FuncType([I32, I32], I32))
```

**Comment by yusuf8ahmed** [comment]
Hi, kyle
Really appreciate the feedback here, I will take a look into this.
